#!/bin/sh /etc/rc.common

USE_PROCD=1
START=50
STOP=50
INTERVAL=3600

start_service() {
  procd_open_instance
  procd_set_param env INTERVAL="${INTERVAL}"
  procd_set_param command /usr/bin/singb/singb-autoupdater-wrapper
  procd_set_param respawn   
  procd_set_param stdout    1
  procd_set_param stderr    1
  procd_close_instance
}