name: Build packages
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build luci-app-singbox-ui
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: singbox-ui:ci

      - name: Create container
        run: docker create --name singbox-ui singbox-ui:ci

      - name: Copy built packages
        run: |
          docker cp singbox-ui:/builder/bin/packages/x86_64/luci/. ./bin/

      - name: Filter IPK files
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          mkdir -p ./filtered-bin
          cp ./bin/luci-app-singbox-ui*.ipk ./filtered-bin/luci-app-singbox-ui_$VERSION.ipk

      - name: Remove container
        run: docker rm singbox-ui

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./filtered-bin/*.ipk
